// Shared services data — consumed by /services (index) and /services/[slug] (individual pages)

export interface ServiceData {
 id: string;       // anchor id on /services
 slug: string;     // URL slug for /services/[slug]
 serviceNumber: string;
 title: string;
 subtitle: string;
 desc: string;
 methodDetail: string;
 whoNeedsTitle: string;
 whoNeedsItems: string[];
 expectTitle: string;
 expectDesc: string;
 whyHere: string;
 image: string;
 metaTitle: string;
 metaDesc: string;
}

export const servicesData: ServiceData[] = [
 {
  id: "ENDODONTICS",
  slug: "root-canal",
  serviceNumber: "01",
  title: "Root Canal Treatment",
  subtitle: "Specialist Endodontics | MDS Endodontist on site",
  desc: "Most people come in dreading a root canal, and leave wondering why they waited so long. When the pulp inside a tooth becomes infected or inflamed due to deep decay, a crack, or repeated dental procedures, a root canal is the only way to save that tooth without resorting to extraction. Left untreated, the infection spreads, causes severe pain, and eventually destroys the bone around the root. At HappyTooth Smile Studio, root canal treatment is performed by Dr. Thushara Sudhakaran, our in-house MDS Endodontist, a specialist who has dedicated her postgraduate training specifically to this field.",
  methodDetail: "The procedure uses a rotary endodontic system with nickel-titanium files that are more flexible and precise than manual instruments. Where cases warrant it, magnification is used to improve accuracy during canal preparation and cleaning. Most straightforward cases can be completed in a single appointment. Complex teeth, molars with additional canals, curved roots, calcified canals, may require a second visit. After treatment, the tooth is sealed and restored with a crown to protect it from fracture under biting forces.",
  whoNeedsTitle: "Who needs it:",
  whoNeedsItems: [
   "Severe or worsening toothache",
   "Lingering sensitivity to heat or cold",
   "Pain on biting or chewing",
   "Swelling near a tooth or gums",
   "A tooth that has gone dark after trauma",
  ],
  expectTitle: "What to expect:",
  expectDesc: "Local anaesthesia, no pain during the procedure, and mild soreness for 1 to 2 days post-treatment. Most patients return to normal the next day.",
  whyHere: "Having a dedicated MDS Endodontist on site, not a referral elsewhere, means complex root canals are handled with specialist-level expertise from the first appointment.",
  image: "/images/indian_rct_procedure.png",
  metaTitle: "Painless Root Canal Treatment in Thiruvananthapuram | HappyTooth",
  metaDesc: "Specialist root canal treatment by MDS Endodontist Dr. Thushara Sudhakaran. Single-sitting RCT available. Serving Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "COSMETIC",
  slug: "smile-designing",
  serviceNumber: "02",
  title: "Smile Designing",
  subtitle: "Cosmetic | Restorative | Customised Treatment Planning",
  desc: "Your smile is usually the first thing people notice, and it shapes the impression you make, consciously or not. Smile designing is not a single procedure but a carefully planned combination of treatments that work together to achieve the result you want. It might involve veneers, crowns, whitening, gum correction, orthodontic adjustments, or a mix of these, depending entirely on what your teeth and face need.",
  methodDetail: "We begin with a thorough evaluation of your teeth, their alignment, the shape and position of your gums, and how your smile interacts with your lips and facial proportions. We then create a digital smile preview so you can see the anticipated outcome before any clinical work begins. This step is non-negotiable, you approve the design, and only then do we proceed. Smile designing is not about making everyone look the same. A well-designed smile looks natural, fits your face, and enhances rather than overwhelms your features. The result should look like the best version of your own teeth, not someone else's.",
  whoNeedsTitle: "Common concerns addressed:",
  whoNeedsItems: [
   "Stained or discoloured teeth",
   "Chipped, uneven, or jagged edges",
   "Visible gaps or spacing issues",
   "Asymmetric alignment or gummy smile",
   "Worn, short, or mismatched old restorations",
  ],
  expectTitle: "Treatment timeline:",
  expectDesc: "Varies by case. Simple smile makeovers (whitening + veneers on front teeth) can be completed in 2 to 3 visits over 2 to 3 weeks. More comprehensive cases involving multiple teeth and gum correction may take 4 to 8 weeks.",
  whyHere: "Our first step is always a consultation and smile assessment, with no commitment required at that stage.",
  image: "/images/happytooth-varkala1.jpg",
  metaTitle: "Smile Designing & Digital Smile Makeover in Thiruvananthapuram | HappyTooth",
  metaDesc: "Transform your smile with HappyTooth's digital smile design service. Veneers, whitening, gum correction — planned to suit your face, not a template. Trivandrum.",
 },
 {
  id: "Orthodontics",
  slug: "aligners-braces",
  serviceNumber: "03",
  title: "Aligners & Braces",
  subtitle: "Orthodontics | Children & Adults",
  desc: "Crooked, crowded, or gapped teeth are among the most common dental concerns we see, and they matter beyond aesthetics. Misaligned teeth are harder to clean, wear unevenly over time, and can contribute to jaw joint problems and bite-related headaches. Orthodontic treatment corrects these issues by moving teeth into their proper positions over a planned period of time. We offer three main orthodontic options.",
  methodDetail: "Traditional metal braces remain the most reliable and cost-effective choice for significant corrections, they work efficiently across all age groups and allow precise control for complex tooth movements. Ceramic braces function the same way but use tooth-coloured brackets, making them far less conspicuous while delivering equivalent results. Clear removable aligners are the preferred choice for adults who want to straighten their teeth without visible appliances, they are worn throughout the day, removed only for eating and cleaning, and changed every 1 to 2 weeks as treatment progresses. For children, early orthodontic assessment (from around age 7 to 8) allows us to identify developing bite problems and address them early.",
  whoNeedsTitle: "Aligners vs. braces:",
  whoNeedsItems: [
   "Aligners are suitable for mild to moderate misalignment",
   "Braces are preferred for complex corrections, rotations, and bite issues",
   "Your clinical assessment will clarify which option applies to you",
   "For adults, age is not a barrier as long as gums and bone are healthy",
   "After treatment, retainers are essential to hold results permanently",
  ],
  expectTitle: "Treatment duration:",
  expectDesc: "Mild corrections: 6 to 9 months. Moderate cases: 12 to 18 months. Complex full-arch alignment: 18 to 24+ months.",
  whyHere: "We design orthodontic setups tailored to your comfort and visual requirements, balancing ceramic brackets, metal rigs, or clear aligners.",
  image: "/images/indian_aligners.png",
  metaTitle: "Braces & Clear Aligners in Thiruvananthapuram | HappyTooth",
  metaDesc: "Metal braces, ceramic braces & clear aligners for children and adults. Specialist orthodontic treatment at HappyTooth, Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "TeethWhitening",
  slug: "teeth-whitening",
  serviceNumber: "04",
  title: "Teeth Whitening",
  subtitle: "Cosmetic | In-Clinic Professional Treatment",
  desc: "Tooth colour naturally changes over time. Tea, coffee, red wine, certain spices, and everyday use leave behind staining that regular brushing simply cannot remove. The result is teeth that look dull or yellow, not because of poor hygiene, but because of surface and subsurface discolouration that requires a clinical-grade whitening agent to address.",
  methodDetail: "Professional in-clinic whitening delivers noticeably brighter teeth in a single appointment, a result that over-the-counter whitening strips and trays cannot match. Before treatment, we assess your enamel condition and gum health to confirm that whitening is appropriate for your case. Sensitivity, existing restorations, and the type of staining all factor into how we approach your treatment. The whitening agent is applied carefully to the tooth surfaces with gum protection in place, and activated over a controlled period. Results are calibrated to your starting shade to ensure natural brightness.",
  whoNeedsTitle: "Best candidates:",
  whoNeedsItems: [
   "Patients with extrinsic (surface) staining from food & drink",
   "Patients with natural age-related yellowing of enamel",
   "Note: Less suitable for tetracycline staining (internal issues)",
   "Note: Internal discolouration is better addressed with veneers",
   "Note: Crowns, veneers, and composite fillings do not whiten",
  ],
  expectTitle: "How long it lasts:",
  expectDesc: "Results typically last 12 to 24 months with normal dietary habits. Avoiding heavy tea, coffee, and tobacco significantly extends the effect. A take-home kit can be provided for maintenance.",
  whyHere: "We calibrate whitening intensity to match your facial profile, avoiding an artificial chalky look.",
  image: "/images/teeth_whitening_smile.png",
  metaTitle: "Professional Teeth Whitening in Thiruvananthapuram | HappyTooth",
  metaDesc: "In-clinic professional teeth whitening at HappyTooth. Results in one appointment, calibrated to look naturally bright. Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "Pediatric",
  slug: "paediatric-dentistry",
  serviceNumber: "05",
  title: "Paediatric Dentistry",
  subtitle: "Children's Dental Care | Ages 1 and above",
  desc: "A child's first few visits to the dentist have a lasting effect on how they feel about dental care for the rest of their life. A frightening early experience can lead to avoidance that causes real harm over years. That is why we approach children's dentistry differently, with unhurried appointments, a calm environment, and a manner that helps children feel safe rather than anxious. We see children from the eruption of their first tooth.",
  methodDetail: "Early appointments are as much about familiarity as they are about clinical examination, getting the child comfortable with the chair, the lights, and the dentist before any treatment is ever needed. As they grow, we monitor tooth development, watch for crowding or bite problems, and treat cavities in milk teeth before they affect the permanent dentition underneath. Preventive treatment is a major part of what we do. Pit-and-fissure sealants are applied to grooves of back teeth, where decay almost always begins. Fluoride application strengthens enamel during critical years. For habits like thumb sucking, mouth breathing, or tongue thrusting, we provide habit-breaking appliances.",
  whoNeedsTitle: "Services for children:",
  whoNeedsItems: [
   "First dental check-ups & oral hygiene habit guidance",
   "Cavity fillings and treatment in milk teeth",
   "Pit-and-fissure sealants for cavity prevention",
   "Professional fluoride application to strengthen enamel",
   "Space maintainers and habit correction appliances",
  ],
  expectTitle: "First visit age:",
  expectDesc: "Ideally by age 1, or within 6 months of the first tooth erupting. At the latest, before age 3. We encourage parents to stay in the room to help the child stay calm.",
  whyHere: "Our specialized pediatric care is built around patience, play, and positive associations, making visits something children look forward to rather than fear.",
  image: "/images/indian_pediatric_dentist.png",
  metaTitle: "Paediatric Dentistry for Children in Thiruvananthapuram | HappyTooth",
  metaDesc: "Child-friendly dental care from age 1. Check-ups, fillings, sealants, fluoride & habit correction at HappyTooth, Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "DentalImplants",
  slug: "dental-implants",
  serviceNumber: "06",
  title: "Dental Implants",
  subtitle: "Restorative | Permanent Tooth Replacement",
  desc: "A missing tooth is more than a gap in your smile. Within months of losing a tooth, the bone underneath begins to resorb, it shrinks because there is no longer a root stimulating it. Neighbouring teeth tilt into the space. The opposing tooth over-erupts. Biting becomes uneven, and over years this creates a cascade of problems that become harder and more expensive to fix. A dental implant addresses all of this.",
  methodDetail: "A small titanium post is placed into the jawbone where the root of the missing tooth used to sit. Over 3 to 6 months, the bone fuses around it in a process called osseointegration. Once this is complete, a ceramic crown is attached to the implant, one that is shaped and shaded to match your surrounding teeth, and functions exactly like a natural tooth. You brush it, floss around it, and eat with it without any restriction. Every implant case at our clinic begins with a proper assessment. Digital X-rays confirm bone availability, and complex cases use CBCT scans for precise anatomical planning.",
  whoNeedsTitle: "Candidacy requirements:",
  whoNeedsItems: [
   "Adequate bone volume to support the titanium post",
   "Good general health (most adults are ideal candidates)",
   "Uncontrolled diabetes must be managed before placement",
   "Active gum disease must be treated prior to surgery",
   "Smoking habits should be reduced to ensure implant survival",
  ],
  expectTitle: "Treatment timeline:",
  expectDesc: "3 to 4 months healing after placement (longer if bone grafting is needed), followed by crown fitting. Total duration is typically 4 to 6 months from placement to final restoration.",
  whyHere: "Implants, when properly placed and maintained with regular cleaning and check-ups, routinely last 15 to 25+ years. Many last a lifetime.",
  image: "/images/dental_implant_model.png",
  metaTitle: "Dental Implants in Thiruvananthapuram | HappyTooth",
  metaDesc: "Permanent tooth replacement with dental implants at HappyTooth. Titanium implants + ceramic crowns. Digital planning. Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "Restorative",
  slug: "crowns-bridges",
  serviceNumber: "07",
  title: "Crowns & Bridges",
  subtitle: "Restorative | Fixed Prosthetics",
  desc: "A dental crown is a full-coverage restoration that fits over a damaged or weakened tooth, restoring its original shape, size, strength, and appearance. It is the appropriate treatment when a tooth has too little natural structure remaining for a filling to be reliable, after a root canal, a large fracture, or severe wear. A crown protects the remaining tooth structure and allows the tooth to function normally under biting forces.",
  methodDetail: "A bridge fills the gap left by a missing tooth without implants. It consists of a false tooth (called a pontic) anchored on both sides by crowns placed over the adjacent teeth. The result is a fixed, non-removable restoration that looks and functions like natural teeth. We work primarily with zirconia and tooth-coloured ceramic materials. Zirconia is exceptionally strong, suitable for back teeth that bear high biting forces, and is also highly aesthetic. Full-ceramic crowns on front teeth offer the most natural-looking result, mimicking natural enamel light transmission.",
  whoNeedsTitle: "Crown procedure & facts:",
  whoNeedsItems: [
   "Takes two appointments in most clinical cases",
   "First visit: tooth preparation and precision impression",
   "Second visit (10-14 days later): crown fitting and cementation",
   "A temporary crown is worn during the interim period",
   "Bridges require preparing the adjacent supporting teeth",
  ],
  expectTitle: "Bridge vs. Implant:",
  expectDesc: "A bridge is faster and lower in cost but involves preparing adjacent teeth. An implant preserves neighbouring teeth completely and is a more independent solution. We discuss both options before proceeding.",
  whyHere: "We use hospital-grade prosthetics and zirconia overlays that resist discoloration and last 10 to 15+ years under heavy chewing pressure.",
  image: "/images/before-after.webp",
  metaTitle: "Dental Crowns & Bridges in Thiruvananthapuram | HappyTooth",
  metaDesc: "Zirconia and ceramic dental crowns and bridges at HappyTooth. Restore damaged or missing teeth. Two-appointment process. Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "DentalVeneers",
  slug: "dental-veneers",
  serviceNumber: "08",
  title: "Dental Veneers",
  subtitle: "Cosmetic | Porcelain & Composite",
  desc: "Veneers are ultra-thin ceramic or composite shells, custom-fabricated and permanently bonded to the front surfaces of the teeth. They are one of the most versatile cosmetic procedures in dentistry, capable of addressing chipped or worn edges, uneven tooth shapes, persistent staining that does not respond to whitening, small gaps, and minor misalignment that would otherwise require orthodontic treatment.",
  methodDetail: "Porcelain veneers are crafted in a dental laboratory from pressed or layered ceramic. They are colour-stable, highly resistant to staining, and possess a translucency that closely mimics natural enamel. When bonded properly, they are remarkably durable. Composite veneers are applied directly in the clinic using tooth-coloured resin, they can be completed in a single appointment and are more economical, but are less stain-resistant and may need replacement or refinishing after 5 to 7 years. Enamel preparation is minimal but permanent.",
  whoNeedsTitle: "Veneers are best for:",
  whoNeedsItems: [
   "Front teeth with persistent, deep tetracycline stains",
   "Minor chips, cracks, or worn edges on front teeth",
   "Closing small, visible gaps without braces",
   "Correcting minor tooth size discrepancies",
   "Veneers are typically placed on the upper front 6 to 10 teeth",
  ],
  expectTitle: "Longevity expectations:",
  expectDesc: "Porcelain veneers: 10 to 20 years with proper oral hygiene. Composite veneers: 5 to 8 years. Both require avoiding excessive biting force on bonded surfaces.",
  whyHere: "We prepare detailed wax-ups and digital previews so you can inspect the size, shape, and shade before any permanent tooth structure is altered.",
  image: "/images/indian_veneers_smile.png",
  metaTitle: "Dental Veneers in Thiruvananthapuram — Porcelain & Composite | HappyTooth",
  metaDesc: "Porcelain and composite dental veneers at HappyTooth. Fix chips, stains, gaps and uneven teeth. Digital preview before treatment. Murukkumpuzha, Trivandrum.",
 },
 {
  id: "GumCare",
  slug: "gum-care",
  serviceNumber: "09",
  title: "Gum Care & Periodontics",
  subtitle: "Periodontics | Gum Disease Treatment",
  desc: "Gum disease is the leading cause of tooth loss in adults, and it is almost entirely silent in its early stages. Most patients do not notice it until it is already causing significant damage. The warning signs, bleeding during brushing, gums that look swollen or darker than usual, a persistent unpleasant taste, or teeth that appear longer because the gums have receded, are often dismissed as minor issues. They are not.",
  methodDetail: "In its early stage (gingivitis), gum disease is fully reversible with professional cleaning and improved oral hygiene. Once it progresses to periodontitis, the supporting bone around the teeth is lost, and bone does not regenerate on its own. The aim at this stage shifts from reversal to arrest and management. Our gum treatment services range from thorough scaling and root planing (deep cleaning below the gum line, usually under local anaesthesia) to periodontal flap surgery for advanced cases where surgical access is needed to debride deep pockets.",
  whoNeedsTitle: "Common signs of gum disease:",
  whoNeedsItems: [
   "Bleeding during routine brushing or flossing",
   "Red, puffy, or tender gum margins",
   "Persistent bad breath that remains after cleaning",
   "Gums pulling away from teeth (recession)",
   "Teeth feeling loose or food packing between teeth",
  ],
  expectTitle: "Systemic health connection:",
  expectDesc: "Untreated periodontitis is associated with poorer blood sugar control in diabetic patients, increased cardiovascular risks, and complications in pregnancy. Gum care is a medical priority, not just cosmetic.",
  whyHere: "We implement lifelong structured maintenance programmes (scaling/polishing every 3 to 6 months) to arrest periodontitis and protect your jawbone.",
  image: "/images/indian_gum_care.png",
  metaTitle: "Gum Disease Treatment & Periodontics in Thiruvananthapuram | HappyTooth",
  metaDesc: "Specialist gum care and periodontal treatment at HappyTooth. Scaling, root planing, deep cleaning and maintenance. Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "Preventive",
  slug: "scaling-polishing",
  serviceNumber: "10",
  title: "Scaling & Polishing",
  subtitle: "Preventive | Routine Oral Health Maintenance",
  desc: "A professional clean every six months is the most cost-effective thing you can do for your oral health, and yet it is routinely postponed or skipped entirely by most people. The reasoning is understandable: if nothing hurts, why bother? The answer is that by the time something hurts, the problem is usually much larger than it needed to be.",
  methodDetail: "Scaling removes calculus, the hardened mineralised deposits that form when plaque is not fully removed by brushing. Calculus cannot be removed at home, regardless of technique or toothbrush type. Once it forms, it creates a rough surface that attracts more bacteria, triggers gum inflammation, and accelerates bone loss around the teeth. Polishing follows scaling and removes surface staining from tea, coffee, and tobacco while smoothing the enamel surface to make plaque adhesion harder. Early cavities, beginning gum pockets, and cracked enamel are all inspected during this session.",
  whoNeedsTitle: "Recommended frequency:",
  whoNeedsItems: [
   "Every 6 months for most healthy adults",
   "Every 3 to 4 months for patients with active gum disease",
   "Every 3 to 4 months for diabetic patients or heavy smokers",
   "Annual professional cleans for children starting school",
   "Session duration: 45 to 60 minutes, including complete charting",
  ],
  expectTitle: "Post-appointment sensation:",
  expectDesc: "Some patients experience mild sensitivity to cold or hot liquids for 24 to 48 hours, particularly where the gums were inflamed before scaling. This is temporary and resolves as gums heal.",
  whyHere: "Detecting a cavity at 6 months means a small, simple filling. Waiting 2 years can mean a root canal and a crown. We focus on interception.",
  image: "/images/happytooth-varkala12-1.jpg",
  metaTitle: "Teeth Scaling & Polishing in Thiruvananthapuram | HappyTooth",
  metaDesc: "Professional dental scaling and polishing at HappyTooth. Remove calculus, surface stains and prevent gum disease. 45-60 min session. Murukkumpuzha, Trivandrum.",
 },
 {
  id: "ExtractionsWisdom",
  slug: "extractions-wisdom-teeth",
  serviceNumber: "11",
  title: "Extractions & Wisdom Teeth",
  subtitle: "Oral Surgery | Simple & Surgical Extractions",
  desc: "When a tooth is too damaged to save, by decay, fracture, failed previous treatment, or severe infection, extraction is the right decision. Attempting to preserve a tooth beyond its clinical viability leads to ongoing pain, spreading infection, and bone loss that ultimately makes future tooth replacement more difficult. A well-timed extraction, followed by an appropriate replacement plan, is the better outcome. Wisdom teeth are a separate and very common problem.",
  methodDetail: "Most adults do not have enough space in their jaws for all four third molars to erupt fully and correctly. The result is an impacted tooth, one that is partially or fully trapped beneath the gum line, often growing at an angle that pushes against the adjacent molar. Impacted wisdom teeth cause episodic pain, infection in the surrounding gum (pericoronitis), and can gradually damage the roots of the neighbouring tooth if left in place. Before extraction, we take a periapical or OPG radiograph to assess root anatomy and nerve proximity.",
  whoNeedsTitle: "Recovery guidelines:",
  whoNeedsItems: [
   "Simple extractions: mild discomfort for 2 to 3 days, normal eating in a week",
   "Surgical wisdom tooth removal: swelling and discomfort for 4 to 7 days",
   "Bite on sterile gauze for 30 minutes post-extraction",
   "Avoid hot food, carbonated drinks, and tobacco for 24 hours",
   "Do NOT rinse or spit forcefully on the first day to protect the clot",
  ],
  expectTitle: "Surgical safety:",
  expectDesc: "Surgical extractions, where bone removal or tooth sectioning is required, are performed under local anaesthesia with high precision, mapping the dental nerve carefully.",
  whyHere: "We provide detailed written instructions and a direct follow-up call after every extraction, ensuring smooth healing.",
  image: "/images/indian_wisdom_xray.png",
  metaTitle: "Wisdom Tooth Extraction in Thiruvananthapuram | HappyTooth",
  metaDesc: "Simple and surgical tooth extractions including impacted wisdom teeth at HappyTooth. OPG X-ray assessment before all extractions. Murukkumpuzha, Trivandrum.",
 },
 {
  id: "DenturesRehab",
  slug: "dentures-rehab",
  serviceNumber: "12",
  title: "Dentures & Full Mouth Rehabilitation",
  subtitle: "Prosthodontics | Complete & Partial Tooth Replacement",
  desc: "Significant tooth loss, whether from decay, gum disease, trauma, or a combination of these, affects far more than appearance. Chewing becomes restricted, which affects nutrition and digestion. Speech changes. The jaw muscles and joints adapt to the new bite in ways that cause pain over time. Self-confidence diminishes in ways that people often don't openly discuss but universally feel.",
  methodDetail: "Complete dentures replace all teeth in an arch, resting on the gum ridges. Partial dentures replace some teeth, using remaining teeth for support via metal clasps or precision attachments. For patients who want the stability and permanence of fixed teeth, implant-supported dentures offer the most significant upgrade in quality of life. Two to four implants placed in the jaw support a fixed prosthesis that does not move, does not require adhesive, and allows normal biting force. Full mouth rehabilitation combines implants, crowns, bridges, and orthodontic treatment to restore a severely compromised bite.",
  whoNeedsTitle: "Treatment duration details:",
  whoNeedsItems: [
   "Conventional dentures: 4 to 6 appointments over 4 to 6 weeks",
   "Implant-supported prosthetics: 4 to 9 months from placement to delivery",
   "Full mouth rehabilitation: Typically 3 to 9 months depending on complexity",
   "Requires bone structure assessment and detailed bite registration",
   "Removable dentures must be removed and cleaned nightly",
  ],
  expectTitle: "Fixed vs. Removable:",
  expectDesc: "Implant-supported fixed restorations are maintained just like natural teeth (brushing, flossing, check-ups) and eliminate the slip and soreness associated with traditional plates.",
  whyHere: "We custom-design denture bases to match the natural shade of your gum tissue, ensuring the boundary is invisible to others.",
  image: "/images/indian_dentist_consult.png",
  metaTitle: "Dentures & Full Mouth Rehabilitation in Thiruvananthapuram | HappyTooth",
  metaDesc: "Complete & partial dentures, implant-supported prosthetics and full mouth rehab at HappyTooth. Restore bite, function and confidence. Murukkumpuzha, Trivandrum.",
 },
 {
  id: "XraysDiagnostics",
  slug: "diagnostics",
  serviceNumber: "13",
  title: "Digital X-Rays & Diagnostics",
  subtitle: "Diagnostics | Radiation-Reduced Digital Imaging",
  desc: "Every treatment decision we make is only as good as the diagnosis behind it. Accurate, high-quality imaging is not optional, it is the foundation of safe dental care. We use digital radiography as our standard system for intraoral and panoramic X-rays.",
  methodDetail: "Digital X-rays produce sharper, higher-resolution images than conventional film, are available on screen within seconds, and deliver significantly lower radiation exposure, typically 80% to 90% less than conventional film X-rays. Images can be enhanced, zoomed, and compared across appointments to track bone loss or cavity progression. For complex cases (implants, impacted teeth, jaw joint issues), cone beam computed tomography (CBCT) scanning provides a three-dimensional volumetric image of the jaws, allowing us to assess bone density and nerve locations.",
  whoNeedsTitle: "Diagnostics available:",
  whoNeedsItems: [
   "Intraoral digital X-rays (for individual teeth & cavities)",
   "Orthopantomogram (OPG full-mouth panoramic overview X-ray)",
   "Cone beam computed tomography (CBCT) 3D imaging for implants",
   "Intraoral camera live feeds (so you can view your teeth on screen)",
   "Digital impressions using advanced intraoral scanning wands",
  ],
  expectTitle: "Radiation reduction:",
  expectDesc: "Our portable digital X-ray units are heavily shielded, exposing patients to a minute fraction of background radiation, with instant digital processing.",
  whyHere: "We show patients their X-rays on a high-definition chairside monitor and explain the findings, so you know exactly why a treatment is recommended.",
  image: "/images/happytooth-varkala3.jpg",
  metaTitle: "Digital Dental X-Rays & Diagnostics in Thiruvananthapuram | HappyTooth",
  metaDesc: "Digital X-rays, OPG panoramic scans and intraoral diagnostics at HappyTooth. 80-90% less radiation than film X-rays. Murukkumpuzha & Kallambalam, Trivandrum.",
 },
 {
  id: "EmergencyCare",
  slug: "emergency-care",
  serviceNumber: "14",
  title: "Emergency Dental Care",
  subtitle: "Emergency | Same-Day Appointments for Acute Cases",
  desc: "Dental emergencies do not wait for convenient appointment slots. A toothache that builds through the night, a tooth knocked out during a fall, a crown that comes off before an important event, a dental abscess that is causing facial swelling, these are situations where waiting is the wrong choice. Delayed treatment makes most dental emergencies significantly worse.",
  methodDetail: "We keep appointment capacity for emergency cases every day. If you are in acute pain or have sustained dental trauma, call us and explain what has happened. We will assess the urgency, advise you on any immediate steps to take, and get you in as quickly as possible, the same day in most cases. Common emergency situations we handle include severe toothache and abscesses, fractured teeth, avulsed (knocked out) teeth, lost crowns/fillings, and soft tissue injuries to the gums or lips.",
  whoNeedsTitle: "Emergency action steps:",
  whoNeedsItems: [
   "Call us immediately at +91 87144 70808 (K) or +91 73561 00602 (M)",
   "For a knocked-out tooth: Keep it moist in milk or saline, do not touch the root!",
   "Do NOT place aspirin directly on the gum (causes chemical burns)",
   "Apply cold compression externally to reduce facial swelling",
   "Abscess with progressive swelling affecting swallowing is a medical emergency",
  ],
  expectTitle: "After-Hours emergencies:",
  expectDesc: "For after-hours emergencies, our contact details and emergency guidance are available. For life-threatening jaw trauma or airway compromise, proceed to the nearest hospital ER.",
  whyHere: "We make every effort to offer same-day relief, focusing first on stopping pain and controlling infection before planning long-term restoration.",
  image: "/images/indian_emergency_dentist.png",
  metaTitle: "Emergency Dental Care in Thiruvananthapuram — Same Day | HappyTooth",
  metaDesc: "Same-day emergency dental appointments at HappyTooth. Toothache, knocked-out teeth, abscesses, broken crowns. Call now: +91 73561 00602 or +91 87144 70808.",
 },
];

// Lookup helpers
export const getServiceBySlug = (slug: string): ServiceData | undefined =>
 servicesData.find((s) => s.slug === slug);

export const getAllSlugs = (): string[] => servicesData.map((s) => s.slug);
